### ISSUE TITLE
potential bug in hmc.py

### ISSUE THREAD

**Issue by gd-zhang** [ermongroup/a-nice-mc#2]
https://github.com/ermongroup/a-nice-mc/blob/master/a_nice_mc/utils/hmc.py#L108
For different step, it seems that you use the same stepsize. I guess `stepsize` should be replaced with `s`.
@jiamings

**Comment by jiamings** [comment]
True I think using s is what I intended to do; I will fix it. But this is
the "less standard way" of doing it and I don't think this will make too
much of a difference in ESS.

**Comment by jiamings** [comment]
I just did a test run with the best step size that I have with the fixed step size case
- German: 1546 / 5000
- Australian: 1454 / 5000
- Heart: 1894 / 5000

So this even seems similar if not worse than the numbers reported in the paper.

Anyway I pushed a commit 0fd9745 to fix this.
