### ISSUE TITLE
Adding Bootstrap from Existing MCMC to train Bayesian Nets

### ISSUE THREAD

**Issue by Razcle** [ermongroup/a-nice-mc#3]
Hi,

I want to try to use a-nice-mc to sample from the posterior weights of a neural net but in my initial experiments for a relatively small net I find that I'm not able to learn to draw reasonable samples even after 60000 training iterations.

I'm training a one-layer feedforward net with a hidden width of 50 units to perform regression on the Boston housing data-set.

I think the issue is that bootstrapping from the randomly initialised model is inadequate for such a high dimensional space. I'm going to try to bootstrap instead from samples drawn using HMC.

Do you have any advice or thoughts on this before I embark? Would you like to include the bootstrap in the repo?

thanks,

Raza

**Comment by Razcle** [comment]
Here's a traceplot for 10000 samples of the 750 network parameters after 60000 training iterations. As you can see, the acceptance rate is critically low (around 0.002).

![net_trajectory](https://user-images.githubusercontent.com/10298740/42329322-50535764-8068-11e8-9257-ed1bed0d4439.png)

**Comment by jiamings** [comment]
See the lines here for the bootstrap code: [L142-L150](https://github.com/ermongroup/a-nice-mc/blob/master/a_nice_mc/train/wgan_nll.py#L142-L150). 

I think you can use HMC directly by changing it with a HMC sampler.

**Comment by jiamings** [comment]
Would be awesome if you implement it and create a PR.

**Comment by Razcle** [comment]
Great thanks. It ICML next week but will try to make a start and submit something soon.

**Comment by Razcle** [comment]
Change has now been merged.
